sudo: required
language: bash
services: docker
dist: trusty

branches: 
  only: 
    - master

before_install:
  - docker build -t eswork/dotnet-build:1.1.2 .
  
script: 
  - docker run -it eswork/dotnet-build:1.1.2 dotnet new