sudo: required
language: bash
services: docker

branches: 
  only: 
    - master

before_install:
  - docker build -t eswork/dotnet-build .
  
script: 
  - docker run -it eswork/dotnet-build dotnet new