version: '2'
services: 
  dotnet-build:
    build: .
    image: eswork/dotnet-build:2.0.0
    volumes:
      - /srv/dotnet_build:/var/dotnet_home
      - /srv/dotnet_build/packages:/root/.nuget/packages
      - /srv/dotnet_build/node_modules:/usr/local/lib/node_external_module
